sudo: required

language: python

dist: xenial

services:
  - redis-server
  - mysql
  - docker

python:
  - "3.7"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_DONT_LOAD_ENV=1

cache:
  - pip

before_install:
  - pip install -U pip

install:
  - make
  - pip install codecov

script:
  - pipenv run make test

after_success:
  - codecov

deploy:
  - provider: script
    script: bash ./docker-deploy.sh master
    on:
      branch: master

  - provider: script
    script: bash ./docker-deploy.sh develop
    on:
      branch: develop

notifications:
  slack:
    secure: W/1DnXH/cJUm3wyu6uQRp8pQFi3vN6h5FgHapaKP2RwOqHqIg+FWGCRRIHEcg8stpf296grD1kbs0ipDjuV5uUXwZ0p/HKsdR6gIFzod3LzEQUNg5sLqjIEDqkIZCA2UJIZPX5RcEzYL6Mkp6Lvbi1/hL+PE8guVVVl7r5/xZ0TRd6jK8pY5unYeCjURjOiHr/GvP4RDici7UwbgYMo0tCOKTe5LT03nVO8+NUeyRoQDQApaf6zpKmdtBaJb3V+GfIAnvEXYI0yGN3T8xLiKKRvzFPLGIV4fN29SwUOTP3hmwDj0XN+F0QfipmNiJQ7oX+hwWxR4wV24KTkFGA/fBn7VC+HOeRrt9gu0hW6t/XBWzyVlW/6Nz7yRJ1iKcub75OhZ+rqC04ni2FJJeef+B/9sH/9MKvQzadneHpyaCtn+8bB9DqY3gXQv9R14lXLHKHakg+R0ACcidTDzOLrDyfKnFjp+pGAudYYD5liGFCJHJc00D3Obx7osU/An5rxOYkYosmrYwCIQ4qb9RvJWFfD3QjHf+x1CHQJbRWDVJaUJ5BK6CwTBnNDSb9g7vBpJWTL0d1VTiT+5JdpCMCbxtT5iQc5gwDSr1EkGr+ZMCQuxxx/qqW/VVv6DE1vA7CPg6EPZFOiMjpamM7cDaJwOskXJUywWcQpNQUIsmhx1cqg=
  webhooks:
    urls:
      - secure: xF+9afjC75pYKzwBg2+KH9f9xRdYAoWfmpEWEYk6qbfmfeBBdhwEqiP42OxaCgoRRSWrkXfYpvU+IDEiVjUR8M17YtWkwVjP5QUiAOR3dBhZCe0mXVTyUUd29cRG4zHOgip6/4n0LjAVh4EZJTQZTtzy3BZLAT62cwJYG4n75w0FM0zClDmChtg/farsGdcvmpU0Pu2adq1HynTurgmVRoMdYBVGBv2swqWhUxJM0QjkJlgwP9VL4dnOo9REFucmt0vWXCINZI9SSytiSlHr+G1XitM9cIQN5snetx3NfJukGROdj7wXSeoOWMHzOQK/lDmYwnkPuu60Ku97Hewa/SXvnbSFOeQ1f+T3iaNejYMbgEJ5RMcY8Bm/3i/OVT4XURz3zqR17bbF634scHlG5Zdwl/0LgHG/w0+JrFO9I/WySI6kOA/xLN0yGUaRnjLCjgS9+8PqDm488b2HJKZse7joP6EYuMgM4lOood72R7nAH3i1VE/2h3ciDtXadpU4ZLd84tFQ578dP7BAsO6D+bJzp5EGuZ7d4X7Rniuc5YV/Fc2iXaCxc8A7yWaRO0VMNUKxLw3yo3WrVvYrS+fDXOOIMSD0A+SjaCDYEeb2Yl1so2pGuoWmV/wKQYXeLX/UYnkQ8Lnvnp30edc+2hwGZu89ec59MSVDzX33eWOHaGU=
    on_failure: never
    on_cancel: never
    on_error: never
